# Generated by Django 3.2.8 on 2021-10-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='careerform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('applyfor', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.IntegerField()),
                ('aboutself', models.TextField()),
                ('resume', models.FileField(upload_to='MyFiles')),
            ],
        ),
        migrations.AlterField(
            model_name='signupmaster',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
