# Generated by Django 3.2.8 on 2021-10-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211020_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='careerform',
            new_name='careermaster',
        ),
    ]
