# Generated by Django 3.2.8 on 2021-10-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_careerform_careermaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermaster',
            name='applyfor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='mobile',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='state',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='careermaster',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
