# Generated by Django 3.2.8 on 2021-10-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211021_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='inquirymaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('inquiry1', models.CharField(max_length=30)),
                ('inquiry2', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
