# Generated by Django 3.2.8 on 2021-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_inquirymaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careermaster',
            name='experience',
            field=models.CharField(max_length=20),
        ),
    ]
