# Generated by Django 3.2.8 on 2022-01-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_careermaster_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signupmaster',
            old_name='username',
            new_name='email',
        ),
    ]
