# Generated by Django 3.2.8 on 2022-01-11 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_username_signupmaster_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careermaster',
            old_name='username',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='inquirymaster',
            old_name='username',
            new_name='email',
        ),
    ]
